version: "3.8"
services:
  mongoservice:
    image: mongo
    container_name: mongoservice
    environment:
      - PUID=1000
    volumes:
      - ./data:/data/db
    restart: unless-stopped

  backendhanews:
    build: ./ohMyHackerNews-backend
    ports: 
      - 5000:5000

  frontendhanews:
    build: ./ohMyHackerNews-frontend
    ports: 
      - 8080:8080
      - 80:80
